### ISSUE TITLE
Charts in file breaks roundtrip

### ISSUE THREAD

**Issue by johnyesberg** [SheetJS/sheetjs#111]
## Roundtrip test program

``` javascript
    var xlsx = require('xlsx');
    var book = xlsx.readFile('test/reports/Book1.xlsx',{cellStyles:true,bookDeps:true});
    xlsx.writeFile(book, 'test/reports/Book1-out.xlsx');
```
## Roundtrip works with no chart
- Create a brand new spreadsheet.
- In Sheet1!A1 type "Sheet 1"
- In Sheet2!A1 type "Sheet 2"
- In Sheet3!A1 type "Sheet 3"
- Save as Book1.xlsx. 
- Output from roundtrip shows appropriate entries in cells.
## Roundtrip fails with chart present
- On Sheet1, select cell A1, and insert some kind of chart (e.g. Column chart).
- Right click on chart and "Move Chart..." to New Sheet Chart1 (which appears to left of Sheet1) 
- Run roundtrip
- Resulting output has three sheets (and no chart).
  - Sheet1 is blank
  - Sheet2 has 'Sheet1' in cell A1
  - Sheet3 has 'Sheet2' in cell A1
- During parsing, book.Sheets.Sheet1['!ref]===undefined

It seems that the presence of the Chart is confusing the parser when it determines the names of the sheets.

**Comment by jbergknoff** [comment]
I'm running into this issue, also. Any progress on it?

**Comment by SheetJSDev** [comment]
We now save charts as worksheets with a `!type` field set to `"chart"`, but they are saved as regular worksheets.  We are working out the logistics of actually saving chartsheets as chartsheets

**Comment by jacobq** [comment]
> We are working out the logistics of actually saving chartsheets as chartsheets

@SheetJSDev Is there a place where we can check the progress of this work? (It's been 18+ months, and the lack of ability to preserve existing "special content" like charts is the only limitation blocking use of this library in my application.)

**Comment by Nisgrak** [comment]
Something new?

**Comment by beingke** [comment]
Bump

**Comment by SheetJSDev** [comment]
For roundtripping, we offer a special [Pro Edit build](https://sheetjs.com/pro) which, instead of trying to read and write the charts properly, surgically edits the underlying data blocks to enable preservation.

Based on our experience offering a component to read and write the basic chart types, a proper roundtrip is certainly possible.  Unfortunately Excel is adding new chart types with each major release (new charts were added in Excel 2016 and Excel 2019), and keeping up with the changes is beyond the scope of what a small number of unpaid volunteers can support.
