### ISSUE TITLE
XLSX.read with a utf-8 string sometimes gives incorrect results

### ISSUE THREAD

**Issue by kdeclerck** [SheetJS/sheetjs#1177]
When I do 
```javascript
XLSX.read("Header1\r\nA looooonger column value", {
    type: 'binary',
    raw: true,
    cellText: true
});
```

Gives me this result:
```json
{
    "SheetNames": [
        "Sheet1"
    ],
    "Sheets": {
        "Sheet1": {
            "A1": {
                "v": "Header1",
                "t": "s"
            },
            "A2": {
                "v": "",
                "t": "s"
            },
            "A3": {
                "v": "A looooong",
                "t": "s"
            },
            "B3": {
                "v": "er column",
                "t": "s"
            },
            "C3": {
                "v": "value",
                "t": "s"
            },
            "!ref": "A1:C3"
        }
    }
}
```

This result seems incorrect to me. I'd expect a workbook with A1: "Header1" and A2: "A looooonger column value". Am I missing something? Thanks in advance!

**Comment by SheetJSDev** [comment]
Since the file contains no common delimiter (tab or comma or semi) it is erroneously interpreted as lotus formatted text (PRN).  The immediate fix on your end is to prepend with `sep=,\n` (that's Excel's magic for forcing a delimiter).  At this point, it probably makes sense to phase out that whole function, which is fortunately a one-line fix.  Feel free to submit this as a PR: https://github.com/SheetJS/js-xlsx/blob/master/bits/40_harb.js#L844

```diff
-		return prn_to_sheet_str(str, opts);
+		return dsv_to_sheet_str(str, opts);
```

**Comment by garrettluu** [comment]
Looks like this issue has been fixed. `PRN: false` is the new default, and running
```js
var wb = XLSX.read("Header1\r\nA looooonger column value", {
    type: 'binary',
    raw: true,
    cellText: true
});
```
gives us the expected result:
```
> wb.Sheets
{ Sheet1:
   { A1: { t: 's', v: 'Header1' },
     A2: { t: 's', v: 'A looooonger column value' },
     '!ref': 'A1:A2' } }
```
