### ISSUE TITLE
Getting time zone added into date while converting string to date 

### ISSUE THREAD

**Issue by mansimehta217** [SheetJS/sheetjs#1194]
Hi,

I am getting date in string format from back end ,in front end am converting it into date type by using cell.t= 'd' and providing it format by using cell.z = 'mm/dd/yyyy'. So that it getting convert into date but am also getting time stamp appended to date. i don't need the time stamp i just need date. and other issue is the date which is getting display on screen is decremented by one. Please refer to below code and screenshot. any help will by appreciated .

<img width="327" alt="code" src="https://user-images.githubusercontent.com/41694089/43209319-f2f459aa-9049-11e8-9254-b6f75923a019.PNG">

![image](https://user-images.githubusercontent.com/41694089/43209415-254499e2-904a-11e8-971a-fd55625adbd2.png)

**Comment by rafael-andrade** [comment]
I am having exactly the same issue, but my problem is a little beyond yours. I will send this spreadsheet to an endpoint that will check if data exists in DB, if so, I will check if changed, if so, I will update it on database. As it cannot recognize the timezone, it will always say that the Date is different from what exists in DB and will update the DB with wrong values. I am trying to get a way with it, if I find a solution I will port here, if you get a solution share with me too.

**Comment by ArcIX** [comment]
Hello. Sorry for reviving this thread but I see that this is still open and I really need a workaround for this. Otherwise, I'll just be trying out a different Excel library. I tried setting cellDates property to true but it did not really change anything. I do have a hypothesis as to what causes this issue though. It seems at some point when the date gets converted to a number, something adds a decimal to it. The added timestamp doesn't seem to change because I've been trying to fix this for 3 hours and the timestamp stays the same. The timestamp I get, which is 8:00:43 AM, is different than OP's though. I tried adding my own timestamp to the date I want to input and I got a different timestamp! My input was '2019-04-03 05:34:23.1234' with a format of 'mm/dd/yy' and the output became '03/04/2019  5:35:06 AM'. This is very odd behavior indeed.

**Comment by SheetJSDev** [comment]
@mansimehta217 @rafael-andrade the overarching problem is that Excel's dates are timezone-dependent.  The date codes are differences from an epoch which depends on the timezone of your computer.  So getting something that works correct in your time zone requires a bit of date manipulation.  That logic has been changed since the issue was raised, please update and report back.

@ArcIX you are finding a different issue.  The main epoch is the beginning of 1900 for Excel.  Depending on your timezone, there may have been a second-level offset.  `Europe/Paris` used to be UTC +0:09:21 and shifted to whole-hour offsets from UTC in the year 1911.  This is a problem because Chrome/Node do not have the correct timezone offset data, as reported in https://bugs.chromium.org/p/v8/issues/detail?id=7863
