### ISSUE TITLE
Some text in string cell broken Exel

### ISSUE THREAD

**Issue by Lebed71** [SheetJS/sheetjs#1341]
Hello! I have a generated file. In Numbers or LibreOffice he open correct. But if I open he by Excel all broken. Excel error log don't give anything info. Can you please check it? Archive with file in attach
[big6.xls.zip](https://github.com/SheetJS/js-xlsx/files/2552232/big6.xls.zip)

**Comment by SheetJSDev** [comment]
There's a neat BIFF format validator at https://www.microsoft.com/en-us/download/details.aspx?id=26794  -- the output gives you a sense for where to look in the binary stream.

One cell has an extremely long string, whose byte representation is about 10K bytes.  Excel enforces this 8224 byte rule (so writers would have to create "Continue" records and split up the original string into chunks) but other tools don't.  Since we aren't generating the continue structure, Excel is choking.

To generate a valid file, try taking a slice of the first 1000 characters of the string.

**Comment by Lebed71** [comment]
Thanks! Could you please give me link on some information about "Continue records"?

**Comment by SheetJSDev** [comment]
The conceptual overview is covered in [`[MS-XLS] 2.1.4 Record`](https://msdn.microsoft.com/en-us/library/dd943823.aspx).

On the parsing side, the [`slurp` function](https://github.com/SheetJS/js-xlsx/blob/master/bits/76_xls.js#L37) takes a peek at the next record to decide if there is a continuation.

If you are interested in contributing a fix, [`write_biff_rec`](https://github.com/SheetJS/js-xlsx/blob/master/bits/78_writebiff.js#L1) takes a payload and generates the appropriate header and record.  That part should inspect the payload length and, if it is greater than 8224, split it up into blocks of 8224 bytes with Continue records (record type 0x3c)

**Comment by Lebed71** [comment]
@SheetJSDev can you give me some answer please?

**Comment by SheetJSDev** [comment]
When writing long strings using the shared string table (`bookSST: true`), Continue records are generated.

The inline strings (Label records) are capped at 255 characters.  To wrap up the issue, we'd accept a PR that enforces the length by slicing and optionally warning.  The places to slice are

https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L72

```js
			write_biff_rec(ba, 0x0004, write_BIFF2LABEL(R, C, (cell.v||"").slice(0,255)));
```

https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L198

```js
			} else write_biff_rec(ba, "Label", write_Label(R, C, (cell.v||"").slice(0,255), os, opts));
```
