### ISSUE TITLE
vietnamese characters not showing properly

### ISSUE THREAD

**Issue by ghost** [SheetJS/sheetjs#1380]
drop a csv file that contains vietnamese here http://oss.sheetjs.com, but not showing properly.
Result: 
<img width="501" alt="2018-12-10 10 51 40" src="https://user-images.githubusercontent.com/37279799/49708241-c9128580-fc69-11e8-97a1-5bbbed7b7536.png">
It should be:
<img width="269" alt="2018-12-10 10 52 41" src="https://user-images.githubusercontent.com/37279799/49708273-ec3d3500-fc69-11e8-8284-2cced10749ef.png">

**Comment by slimtom95** [comment]
Hi @zhanyuilong what's the charset of your csv? Currently, only 'utf8' (codepage: 65001) is supported by sheetjs for uploaded csv, and it's due to the behavior of `String.fromCharCode` #892 

And as I commented in #892 , I think sheetjs should try decoding the file in given codepage when it detects a csv. @SheetJSDev

**Comment by SheetJSDev** [comment]
The standard codepage in Vietnam is 1258.  You should be able to read the file with the option `codepage: 1258`.  If this issue still persists, please share a file and we can take a closer look.
