### ISSUE TITLE
The library is vulnerable to the CSV injection

### ISSUE THREAD

**Issue by stukalin** [SheetJS/sheetjs#1417]
Steps:
- create a worksheet with a cell with the text `=CONCATENATE("1";"2")`
- export as CSV (I used `XLSX.writeFile(wb, 'test.csv')`)
- open in MS Excel

Expected result:
- the cell is rendered as `=CONCATENATE("1";"2")`

Actual result:
- the cell is rendered as `12`

**Comment by SheetJSDev** [comment]
This is Excel's behavior.

Steps:

- Open Excel and create a new workbook
- Set cell A1 to be the text `=CONCATENATE("1","2")`.  To do this, set the formula to `'=CONCATENATE("1","2")` with the leading apostrophe
- Save as CSV and print the contents

Excel generates

```
"=CONCATENATE(""1"",""2"")"
```

Using the open source build 0.14.1, http://jsfiddle.net/bxy4apgt/ is a live example that just does:

```js
var ws = XLSX.utils.aoa_to_sheet([['=CONCATENATE("1","2")']]);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue1417.csv");
```

And the result, if you inspect the generated file with a text editor, is

```
"=CONCATENATE(""1"",""2"")"
```

Truly unfortunate that Excel doesn't provide a simple way of suppressing CSV auto-calculation.

**Comment by stukalin** [comment]
> This is Excel's behavior.

Yes, it is. But I assume we could make the escaping  of special characters a part of  the library. We could enable/disable it by passing a flag into the `write` function for example.

**Comment by gus-sosa** [comment]
I think this is still a valid issue.
This is a better example:

`@SUM(1+1)*cmd|' /C calc'!A0`

This is going to open up the calculator on windows.

and I agree with @stukalin , we should make the escaping of special characters part of the library.

**Comment by SheetJSDev** [comment]
I disagree with changing the default behavior, but could accept it as an option.

@enghong would it cause any issues if we added this escaping behavior to the `forceQuotes` option?

**Comment by enghong** [comment]
I'm not sure linking the two features together is a good idea. The intent behind `forceQuotes` is just to make sure all fields are wrapped with quotes.

Here, it seems to require extra work to realise the excepted result.

What would be the CSV string to make excel render `=CONCATENATE("1";"2")` or `@SUM(1+1)*cmd|' /C calc'!A0`?

**Comment by SheetJSDev** [comment]
We'd literally have to write a formula that evaluates to those strings:

- `="=CONCATENATE("&CHAR(34)&"1"&CHAR(34)&","&CHAR(34)&"2"&CHAR(34)&")"` in Excel's UI
- `="=CONCATENATE(""&CHAR(34)&""1""&CHAR(34)&"",""&CHAR(34)&""2""&CHAR(34)&"")"` in CSV

Given that SheetJS is identical to Excel in behavior, this type of CSV injection issue is out of scope.  

We might have accepted a sanitized output option (which is why `forceQuotes` and @enghong 's contribution came to mind).  But looking at what we actually have to do, it's probably better to recommend an external sanitizer.

**Comment by gus-sosa** [comment]
@SheetJSDev I know the issue is closed, and that's ok. I want to comment what I did to resolve the excel injection.

`for (var pos in workSheet) {
    var cell = workSheet[pos];
    if (cell.t == "s" && ["+", "-", "@", "="].some(function (ch) { return cell.v.startsWith(ch); })) {//preventing excel injection
        cell.v = "'" + cell.v;
    }
}`

I just insert an apostrophe if the cell starts with **+ - @ +** and that works fine.
For more info:  https://affinity-it-security.com/how-to-prevent-csv-injection/

**Comment by SheetJSDev** [comment]
@gus-sosa if you have time, and can wrap that up in a small function, feel free to add it to the wiki page

**Comment by lukejpreston** [comment]
Sorry for resurrecting an old topic

The solution https://github.com/SheetJS/sheetjs/issues/1417#issuecomment-652569056 doesn't work for formulas, only for cells starting with `+-@` Perhaps something has changed since this comment.

I have this

```js
Object.entries(workSheet).forEach(([origin, cell]) => {
    if (cell.t === 's' && startsWithInjection(cell.v)
    ) {
        const newValue = `'${cell.v}`;
        workbook.Sheets[sheetName][origin].v = newValue;
    } else if (cell.f) {
        workbook.Sheets[sheetName][origin].t = 's';
        const newValue = `'=${cell.f}`;
        workbook.Sheets[sheetName][origin].v = cell.w || newValue;
        delete workbook.Sheets[sheetName][origin].f;
        delete workbook.Sheets[sheetName][origin].w;
    }
});
```

This works for CSVs, but when I do it for XLSX files it seems to save the cell as a formula and not a string. Could someone give me advice on what I am doing wrong?

**Comment by lukejpreston** [comment]
Sorry ignore my comment, it does save the file correctly, I am just blind
Hopefully, the code snippet helps someone else in the future
