### ISSUE TITLE
READ .xlsx file error

### ISSUE THREAD

**Issue by CHJ1993** [SheetJS/sheetjs#1442]
I get this error when i use js-xlsx to read a (.xlsx) file that save by Mac System

![image](https://user-images.githubusercontent.com/20351482/53678182-36c4cf80-3cf6-11e9-8a2b-ad0ea8b20cd2.png)

**Comment by CHJ1993** [comment]
![image](https://user-images.githubusercontent.com/20351482/53678215-e5691000-3cf6-11e9-9498-b7f146c716c0.png)

this is my code

**I need help**

**Comment by chensongni** [comment]
dont use wps, office instead

**Comment by SheetJSDev** [comment]
This issue was fixed months ago, please do an update.

To summarize, the header CLSID is expected to be zeroes but some writers generate files with a nonzero id, so the error check was removed.  the [CFB dependency version 1.1.1 resolved the problem](https://github.com/SheetJS/js-cfb/commit/8d85fb6e74e3b84e440a3a107b01350bc2b30464)
