### ISSUE TITLE
Support for spreadsheets with images

### ISSUE THREAD

**Issue by ovari** [SheetJS/sheetjs#1450]
How can SheetJS open spreadsheets with images?

Please see attached ods file. Created with LibreOffice
https://www.libreoffice.org/

LibreOffice enables cells to store images
https://wiki.documentfoundation.org/ReleaseNotes/6.1#Images

Images could then used in the Thunderbird Mail Merge add-on:
https://addons.thunderbird.net/addon/mail-merge/

Images could be then also used for photos in the Thunderbird CardBook add-on:
https://gitlab.com/CardBook/CardBook/issues/528
https://addons.thunderbird.net/en-US/thunderbird/addon/cardbook/

What do you think?

Thank you

**Comment by ovari** [comment]
This feature seems to be available in other open-source projects, for example [jExcel](https://bossanova.uk/jexcel)

Embbed images on your cells
https://bossanova.uk/jexcel/examples/images

**Comment by zzyyzz1992** [comment]
@ovari it's not a node framework which can process and export xls files. It's just a web UI framework which can only CRUD on a web without ability to export to a xls file

**Comment by jimmywarting** [comment]
[ExcelJS](https://github.com/exceljs/exceljs#images), google sheet, MacOS Numbers all support image in cells

**Comment by SheetJSDev** [comment]
This is a feature in our [Pro offering](https://sheetjs.com/pro).  I cannot currently say when or if they will be introduced in the open source build, because there are moving parts not really covered well by Sheets, Numbers, Excel online or other software.

The internal units for images is the so-called ["English-Metric Unit"](https://en.wikipedia.org/wiki/Office_Open_XML_file_formats#DrawingML).  An image can be set to span a single cell or range by setting the anchors to the topleft corner of the cells you want to span.  For anything beyond that, because the units are not related to screen dimensions, you need a model for the PPI among other things (as a trivial experiment, in Windows try changing text scaling to 125% or 150%).  This is made even more complex because the column widths themselves are tied to text scaling (try opening files in Windows and in Mac Excel!).

So for the trivial case where an image is anchored in a cell or range of cells (e.g. topleft corner of cell B2 to topleft corner of cell D3), it is easy; for more general cases, it's not so simple.

**Comment by jimmywarting** [comment]
To bad. guess my choice  will become ExcelJS then...

**Comment by SheetJSDev** [comment]
If you can believe, even [Microsoft Office 365 uses this library to power exports](https://tasks.office.com/License.html), and it's extremely hard to shake the feeling that advancing our open source software is merely providing free labor to Microsoft.

**Comment by ovari** [comment]
Hopefully an image handler can be added to the Geary email mail merge add-on. https://gitlab.gnome.org/GNOME/geary/-/issues/660#note_761699

**Comment by ovari** [comment]
> If you can believe, even [Microsoft Office 365 uses this library to power exports](https://tasks.office.com/License.html), and it's extremely hard to shake the feeling that advancing our open source software is merely providing free labor to Microsoft.

Could the SheetJS licence be changed so that this won't happen?

**Comment by SheetJSDev** [comment]
Honestly if you're looking to do something like mail merge, it's easier to just edit the file directly (an approach similar to what https://github.com/optilude/xlsx-template does).  (and yes, we have a Pro component for XLSX/XLSM editing that does something similar, preserving the original file and editing the worksheet data block directly)

On licensing, part of the point of the Apache license is that other companies can use the software.  It's intentionally not AGPL or "BSL" or "SSPL" or some other license to prohibit usage.  Relicensing at this point would be betraying the very users who trusted us in the first place and would only apply to future releases.  [Many people and projects are comfortable doing this](https://github.com/handsontable/handsontable/issues/5831).  In contrast, we think relicensing would destroy the goodwill built up over the years.

The Pro software and related sales is the main reason we can even think about spending time working on the open source software.  We've been trying to find a fair balance with the original mission in mind, and in our view the open source mission is data (reading and writing the data in various spreadsheet formats).  Images, charts, styles, PivotTables, VBA, and the myriad of non-data features are currently not our focus, but that may change in the future.
