### ISSUE TITLE
Sheet_to_json can't convert single row only

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/sheetjs#1453]
I'd like to read only one single row, since I want my headers to be stored seperately from my rows. (E.g. Headers are in Row 1 but Data starts from Row 4, I don't want rows 2 & 3 read so I'm splitting the data sets.)
However, when trying to read for example only range "C1:I1" it returns an empty array.
My attempts:

defining the range directly
 `var aColumns = XLSX.utils.sheet_to_json(worksheet, {range: "C1:I1"});`

defining the range before converting
```
worksheet['!ref'] = "C1:I1";
var aColumns = XLSX.utils.sheet_to_json(worksheet);
```

but neither of this returns anything. aColumns is always empty..

**Comment by TheClonker** [comment]
Hey @sonjadeissenboeck , i just faced the same Problem, try setting `header` to 1 if the problem still exists for you.
`var aColumns = XLSX.utils.sheet_to_json(worksheet, {range: "C1:I1", header: 1});`

The Problem is the offset Variable [here](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L20576) with header: 1 the offset gets set to 0 and the single row is getting processed.

**Comment by reviewher** [comment]
`header:1` generates an array of arrays.  Without it, it will try to generate objects using the first row as header keys.  When the data has a single row, no data rows are generated
