### ISSUE TITLE
Formating number, numeric, currency columns values

### ISSUE THREAD

**Issue by duard** [SheetJS/sheetjs#1458]
How can I format my currency columns to currency format  ?

My original value is 
**163.563,08**
In my exported the value is :
**163,56308**

here is how I'm exporting my data : 
```
const ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(this.tabela.nativeElement);
const wb: XLSX.WorkBook = XLSX.utils.book_new();

XLSX.utils.book_append_sheet(wb, ws, this.titulo);
XLSX.writeFile(wb, `${this.titulo} - ${'GODAIME'} - ${format(new Date(), 'DD-MM-YYYY hh:mm:ss')}.xlsx`);
```

My table is this : 
![Screenshot from 2019-03-15 09-44-55](https://user-images.githubusercontent.com/36894/54432120-0eca6880-4707-11e9-9b37-332c58728ee9.png)

**Comment by sibelius** [comment]
did you figure it out?

**Comment by SheetJSDev** [comment]
The issue is ultimately JS assuming en-US formatting:

```js
parseFloat("163.563,08") // 163.563, a number between 100 and 1000
```

Until we implement locale-aware value parsing, there are a few workarounds:

1) in the table, use the `data-v` / `data-t` / `data-z` attributes to specify the raw numeric value and number format.  They bypass the attempts to parse the strings, but you have to specify the values in US style.

2) emit values in the en-US style ("." is the decimal point and "," is the thousands separator)
