### ISSUE TITLE
while using header option with XLSX.utils.json_to_sheet , headers not overriding

### ISSUE THREAD

**Issue by SandeshSarfare** [SheetJS/sheetjs#1487]
While I try to change header titles by passing array of titles to options like below it does not override the headers. Instead it writes new headers first and original data with old headers again from next cell.

Here is my code

```
const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json, {header: headerColumns});
    const wb: XLSX.WorkBook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Transactions');
    const excelBuffer: any = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    this.saveAsExcelFile(excelBuffer, excelFileName);
```

Also see attached exported file.
[sample.xlsx](https://github.com/SheetJS/js-xlsx/files/3106201/sample.xlsx)

why is it happening? I just want to rename the headers , everything else is working file.

**Comment by dottodot** [comment]
I'm having the same issue as above.

**Comment by SandeshSarfare** [comment]
@dottodot  did you find anything on this one?

**Comment by dottodot** [comment]
@SandeshSarfare Unfortunately not, think one of the maintainers of this project will need to advise on this.

**Comment by HectorJeronimo** [comment]
gfds

**Comment by arvi** [comment]
True. That is why I'm using `aoa_to_sheet`, I find it much cleaner. I was able to create a workaround with `json_to_sheet` by not stating headers option instead making the object key the header label e.g

```javascript
        const jsonSheet = [
          {
            'Transaction No': '912391231',
            Description: 'This is a description',
            Currency: 'USD',
            Amount: '123123',
            'Date Created': '2019-01-01 11:22:33',
          },
          {
            'Transaction No': '912311231',
            Description: 'This is a description',
            Currency: 'USD',
            Amount: '123123.55',
            'Date Created': '2020-01-01 11:22:33',
          },
        ];
        const ws = xlsx.utils.json_to_sheet(jsonSheet);
```

**Comment by paustint** [comment]
>While I try to change header titles by passing array of titles to options like below it does not override the headers. Instead it writes new headers first and original data with old headers again from next cell.

I am experiencing the same problem.

In addition, sheets js is mutating the header array passed in, which is not something I would ever expect.

Example:
```javascript
const header = ['field2', 'field3'];
const data = [{field1: 'foo', 'field2': 'bar', 'field3': 'baz'}]

const worksheet = XLSX.utils.json_to_sheet(data, {header});

console.log(header); // RESULTS:  ["field2", "field3", "field1"]
```

**Comment by SheetJSDev** [comment]
@paustint that's an unrelated issue and should be tracked separately.

@SandeshSarfare @dottodot This is intended behavior.  If you want to overwrite the values in the header cells, use `aoa_to_sheet` and directly modify the header names.


As described in the docs, `header` option is "Use specified column order (default `Object.keys`)".

This option exists because of a fundamental ambiguity.  Suppose you were trying to write the following to a worksheet:

```js
[
  {Price: 1, Name: "a"},
  {Name: "b", Price: 2},
]
```

In what order should fields be written?  If you applied the naive approach of using Object.keys order, you'd get a table like

```
1  |  a
b  |  2
```

That probably doesn't make sense.  So `header` lets you control the order of the output columns.  Each value in the header array is a key that is checked against each object.  So if you pass the header `["Price", "Name"]` you will see

```
1  |  a
2  |  b
```

But if you pass `["Name", "Price"]` you will see

```
a  |  1
b  |  2
```

When a key is present in an object but missing from the header array, it is added to the end

**Comment by paustint** [comment]
>This option exists because of a fundamental ambiguity. Suppose you were trying to write the following to a worksheet:

I would assume that the first row of data would be used to determine the order of all of the following rows to eliminate this ambiguity, assuming the user did not pass in an alternative `header`.

>When a key is present in an object but missing from the header array, **it is added to the end**

This really caught me off guard because every other CSV generation library I have used (which is about 4 or 5 of them at least) have always allowed passing in a list of headers to use as an override which controls both the order and and limits the fields in each row of data to include, while ignoring the rest.

I did end up converting my data into aoa so I could control the structure, which was extremely trivial, but took me some time to figure out because I had the wrong mental model based on how other libraries work.

Thank you so much for your response and explanation.

**Comment by daixixidai** [comment]
@paustint  I found some good solutions to resolve the overriding problem when I searching the question on this website https://blog.csdn.net/qq_37027371/article/details/106022855 .

const header = ['field2', 'field3']; 
const data = [{field1: 'foo', 'field2': 'bar', 'field3': 'baz'}];
const headerdata={field1:"AA",field2:"BB",field3:"CC"};
const aggregation=[headerdata,...data];

//add a row of new headerdata ,then skip the origin head;
const worksheet = XLSX.utils.json_to_sheet(data, {header,, skipHeader:true});

I think this is a friendly solution,but if there is an option which can rename the column will be better.
