### ISSUE TITLE
"[Content_Types].xml" exported from `js-xlsx` contains "macroEnabled" ContentType

### ISSUE THREAD

**Issue by jorangreef** [SheetJS/sheetjs#1501]
I noticed that when creating an XLSX using `js-xlsx`, the resulting `[Content_Types].xml` listing includes an unnecessary `macroEnabled` ContentType, even though the generated XLSX has no macros:

```
<Default Extension="bin" ContentType="application/vnd.ms-excel.sheet.binary.macroEnabled.main"/>
```

This ContentType for the corresponding "bin" extension should only be included if the exported XLSX does in fact have macros.

Otherwise, anti-virus scanners which inspect XLSX ZIPs and scan `[Content_Types].xml` will reject the file thinking it has macros.

**Comment by SheetJSDev** [comment]
So we can reproduce, what anti-virus scanners are tripping based on this?

**Comment by jorangreef** [comment]
At least our inhouse firewall.

**Comment by jorangreef** [comment]
Some scanners will look for .bin files as evidence of macros, but slightly more sophisticated scanners will look through `[Content_Types].xml`, since macro extensions can be reassociated.

**Comment by SheetJSDev** [comment]
`.bin` is the extension used for entries in XLSB files.  Can you test if those files are flagged?  To generate, just change the extension of the file to ".xlsb" or set the option `bookType:  "xlsb"` on write.

**Comment by jorangreef** [comment]
Yes, I am aware of the XLSB format (and we don't flag them), but this issue relates to XLSX files.

**Comment by jorangreef** [comment]
`.bin` is also the extension used for `vbaProject.bin` files inside macro-enabled spreadsheets (`xlsm` etc.).

**Comment by TommyAlfaro** [comment]
i have the same problem , i am getting this message in my firewall :  File Contains VBA Macro blocked , Gateway Anti-virus Alert

**Comment by SheetJSDev** [comment]
@TommyAlfaro is it blocking files with VBA macros (XLSM with bookVBA: true) or is it blocking the XLSX files too?  Can you see if the XLSX export from https://sheetjs.com/demo/table is blocked?  While we're at it, is the XLSB blocked as well?

**Comment by TommyAlfaro** [comment]
Maybe I should explain more,  i am making a docker image which contains an
angular project with your library,   the firewall blocked the container
image.
I probed with the Excel file generated on https://sheetjs.com/demo/table
and wasn't blocked

**Comment by SheetJSDev** [comment]
Let me ask differently: does the module itself (the thing you get when you run `npm install xlsx`) trigger the warning OR do generated files trigger the warning?  You can test if the container is the issue by building a container without the `xlsx` module and seeing if your firewall blocks it.

**Comment by TommyAlfaro** [comment]
I just checked, if i remove xlsx  i don't have problem sending the docker image,
about your question , i don't have issues doing npm install xlsx  because i am doing in my house but when i send the container (to my work place ) is when i have problems.

Tomorrow i'm gonna ask to firewall owner  the log  and i'll send you.

**Comment by SheetJSDev** [comment]
Since the library is capable of reading and writing XLSM files with macros, certain tell-tale strings are in the source.  https://github.com/SheetJS/sheetjs/blob/master/bits/30_ctype.js#L153 for example we need to set a content type to a string with an offensive word like `macroEnabled`.

If you can confirm that the source is causing the issue, we might be able to design a workaround by programmatically generating the word in a way that won't easily be optimized into the offending word.  I'd be curious to know more about why it's being flagged

**Comment by SheetJSDev** [comment]
@TommyAlfaro please follow up and let us know what may be causing issues.

@jorangreef if you have control over the scanner, it should check for the existence of an xl/vbaProject.bin or similar in the file.  If you would like to send a PR to suppress the `bin` record for XLSX, https://github.com/SheetJS/sheetjs/blob/master/bits/30_ctype.js#L258 should filter `CTYPE_DEFAULTS` if `opts.bookType` is `"xlsx"` or not defined
