### ISSUE TITLE
Add support for streaming to xlsx or xlsb

### ISSUE THREAD

**Issue by msahil432** [SheetJS/sheetjs#1566]
**First of all, thanks for the library.**

Second, I need support for streaming files to xlsx or xlsb
Currently there is the support for streaming files as csv, json and html, is there **a workaround** to do the same for xls? 
I mean there is an option to save files as xlsx directly, so may be same can be used here?!

Thanks again.

**Comment by msahil432** [comment]
Well, I found the functionality within the library, at least for my specific case.

I needed to pipe/stream xlsx object as blob or buffer to a client from my express server. And here is the code which I ended up using, as it turns out library provides in built support for buffer and expressJS can send a buffer successfully to the client.

> response.setHeader('Content-Type', 'application/octet-stream');
> response.setHeader('Content-Disposition', 'attachment; filename="File.xlsx"');
> 
> let data = JSON.parse(request.body.data);
> var wb = XLSX.utils.book_new();
> var ws = XLSX.utils.json_to_sheet(data);
> XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
> var wbopts = {
>     type: 'buffer',
>     bookType: "xlsx",
>     bookSST: false
> };
> var wbout = XLSX.write(wb, wbopts);
> response.send(wbout);

In above code, I am writing a file to storage, Converting JSON to XLSX inside code, and client can save the result to file.

As for CSV, here is the code if again, someone wants it:

> ....
> XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
> 
> var stream = XLSX.stream.to_csv(ws);
> stream.pipe(response);

Thanks @SheetJSDev again, for this great library.

**Comment by jedwards1211** [comment]
It's extremely strange that there aren't streaming functions for all supported output formats

**Comment by SheetJSDev** [comment]
Streaming write is supported for simpler formats like CSV.

XLS streaming is tricky thanks to the way the sheet list is stored.  They use [`BoundSheet8`](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/b9ec509a-235d-424e-871d-f8e721106501) records which contain a forward pointer to the location of the worksheet within the blob.  The essential problem, in the case of a multi-worksheet file, is not knowing where the later worksheets are supposed to start.  For the normal non-streaming case, [the worksheets are written first and data is fed into the logic that writes the header before being assembled in the correct order](https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L380)

XLSX and XLSB streaming are definitely more feasible since the workbook metadata can be generated after the worksheets are written.  While there are some structs that have to be built (like the shared string table), they can be held in memory and written after the worksheets.

[Streaming write in the browser is an ongoing discussion](https://github.com/WICG/file-system-access) and we'd be open to revisiting the streaming issues once it is stabilized and best practices are established
