### ISSUE TITLE
Executing VBA script inside  Excel file

### ISSUE THREAD

**Issue by TranBaVinhSon** [SheetJS/sheetjs#1574]
I have some `xlsm` files with VBA script inside and hope that can automatically run VBA script by nodejs code. Is that possible with `js-xlsx` package ?
I have searched for a while but it seems like we only can add VBA script into xlsm files, not execute the code. https://github.com/SheetJS/js-xlsx/issues/626
Any advice is welcome!

**Comment by dtboy1995** [comment]
the same issue!

**Comment by sancarn** [comment]
Out of scope according to https://github.com/SheetJS/sheetjs/issues/994

Unfortunately the VBA decompiler is the primary missing component (even if it was written in another language). Without it it it'll never be executable from this issue.

Win32 API code could at least by called using FFI, so that's not an issue, but decompiler (and compilers for adding code) is the biggest issue for this feature. This will likely never get added. There is more hope in OfficeJS evaluation and add-ins.

**Comment by SheetJSDev** [comment]
To be clear about the feature support and scope, there are different levels of macro support:

1) preserving the macros (read/write the raw data): supported in the open source build

2) extracting or modifying the raw macro code: VBA component in our SheetJS Pro offering

3) evaluating macro code from JS: closed beta with some of our customers, unsure of when a public release will be made.

**Comment by sancarn** [comment]
Glad to hear you are working on OfficeJS support! :D
