### ISSUE TITLE
utils.sheet_to_json return a lot of __EMPTY_ field when I set defVal

### ISSUE THREAD

**Issue by linchen2chris** [SheetJS/sheetjs#1608]
I try to set defVal for empty cell, but it will return a lot of __EMPTY_* field, I check them, it will return 255 field in total, how can I remove these uesless __EMPTY_* column? 
if not, then I have to remove them manually.

**Comment by SheetJSDev** [comment]
The `__EMPTY` fields are generated when data is present in columns that are missing titles.  Without seeing the actual file it is hard to tell the root cause, but it is worth digging into the file to see if there are actually cells with content somewhere in the file.  If you can share a file we can take a closer look.
