### ISSUE TITLE
Changelogs Outdated

### ISSUE THREAD

**Issue by Heartnett** [SheetJS/sheetjs#1728]
The last update, at the time of writing this, was on 2019-08-14.

**Comment by kachkaev** [comment]
@SheetJSDev could you please help with resolving this? I am on `0.16.9` and am seeing an option to upgrade to `0.17.0`. My xlsx-related code is not covered with integration tests, so this feels quite risky.

It'd be great if the `CHANGELOG` file contained the summary of the new features as well as breaking changes, if any. Example: https://github.com/tj/commander.js/blob/master/CHANGELOG.md  

Some projects also maintain summaries on the _releases_ page, e.g. https://github.com/tj/commander.js/releases  
It is often both.

Related: https://github.com/SheetJS/sheetjs/issues/2292 https://github.com/SheetJS/sheetjs/issues/1974 https://github.com/SheetJS/sheetjs/pull/1955

**Comment by SheetJSDev** [comment]
First cut.  If this looks good, send a PR:

```
0.17.0:

- mini build includes ODS parse/write support
- DBF explicitly cap worksheet to 1<<20 rows
- XLS throw errors on truncated records
```

The bump to 0.17.0 rather than 0.16.10 is due to [CVE-2021-32012](https://nvd.nist.gov/vuln/detail/CVE-2021-32012). 
@LivingInSyn wrote [a blog post about how the issue was discovered](https://floqast.com/engineering-blog/post/fuzzing-and-parsing-securely/)

To summarize, DBF files self-report the number of rows and process data in a loop.  It is pretty simple to construct a file with an artificially high row count and no columns.  That would cause the library to create a large number of arrays, destabilizing V8.  This sort of attack does not affect the other formats as they either don't have a worksheet dimension (CSV, PRN), explicitly ignore the reported dimension (SYLK, ETH), or build up worksheets manually (WK1, XLS, XLSX, XLSB, etc).

**Comment by SheetJSDev** [comment]
CHANGELOG backfilled 0.17.0, please let us know if there's an older version that needs a revisit
