### ISSUE TITLE
Large numbers converted to exponential form while exporting

### ISSUE THREAD

**Issue by sanghaiadarsh** [SheetJS/sheetjs#1801]
When we try exporting data to an excel using something like **aoa_to_sheet** or **sheet_add_aoa** large numerical values like **1000000000000** gets converted to the format **1E+12** in the excel file. Any way to stop this from happening?

**Comment by SheetJSDev** [comment]
`1000000000000` in general format is `1E+12`.  Set the cell's number format to `0`

**Comment by cynologic** [comment]
Hello, 
Firstly it's a great package and I'm a fan of it. I have encountered with a problem. Is there a way to prevent formating the large numbers. I've set rawNumbers: true but it's not working.

What I need to achieve having an unformatted cell (89462008012016396601 instead of 8,94620080120164E+019)

My function is as follows:
function htmlTableToExcel(type){
 var data = document.getElementById('tblToExcl');
 var excelFile = XLSX.utils.table_to_book(data, {rawNumbers: true});
 XLSX.write(excelFile, { bookType: type, bookSST: true, type: 'base64'});
 XLSX.writeFile(excelFile, 'ExportedFile:HTMLTableToExcel.' + type);
}

The ss
https://ibb.co/RDKXpny

I would appreciate if you help me with this issue.
Best regards
Juen

**Comment by SheetJSDev** [comment]
@cynologic Please raise a new issue in the future.

That number cannot be exactly represented in JS.  https://git.sheetjs.com/sheetjs/sheetjs/issues/2869#issuecomment-9193 more details.

You need to keep the value as a string.  If you can modify the table, use the overrides in https://docs.sheetjs.com/docs/api/utilities#value-override to force a string cell.  If you cannot modify the table, pass the option `raw: true` to `table_to_book` (https://docs.sheetjs.com/docs/api/utilities#html-table-input more details)
