### ISSUE TITLE
Convert timestamp values to date string

### ISSUE THREAD

**Issue by pradeepntip** [SheetJS/sheetjs#1906]
I have some epoch timestamps in my data set. How can convert them date string while writing to xlsx ?
Any help!!

**Comment by SystemParadox** [comment]
If you've got data that represents dates then you should be giving it to sheetjs as a Date so that it can do the right thing depending on what file format you are writing. Whilst you *could* format it as a string yourself I would strongly recommend against doing that, as it'll end up as a string column in Excel, which is probably not what you want.

Formatting your data set correctly is up to you. You can do this easily with standard JS (read the documentation for the Date class), or by using a library like momentJS.

**Comment by SheetJSDev** [comment]
As @SystemParadox mentioned, if you pass JS Date objects it will write.

JS and Unix share the same epoch (midnight of January 1 1970) but JS timestamps represent milliseconds while UNIX timestamps represent seconds.  Converting from UNIX to JS involves a simple division:

```js
function unix_to_Date(unix) { return new Date(unix * 1000); }
```
