### ISSUE TITLE
Reading stream in SheetJS

### ISSUE THREAD

**Issue by Amine3154518** [SheetJS/sheetjs#1930]
Im working with xlsx and it takes so much time to read from an excel file so Ive made a search and I have found that reading streams make program reads files faster and more performant but I have searched for reading stream syntax in SheetJS but I didnt found so Can u pls help me Im stuck right now

**Comment by SheetJSDev** [comment]
Streams help in certain use cases where hard work can be offloaded to native APIs (for example, using a system utility program instead of pure JS).  No browser-based solution can really take advantage of it, short of rewriting parts in wasm.  So even though there are definite improvements in node contexts, we're hesitant to use something that will degrade browser performance.
