### ISSUE TITLE
Uncaught TypeError: XLSX.read is not a function  with dojo AMD

### ISSUE THREAD

**Issue by adeebgithub** [SheetJS/sheetjs#1937]
Hi
When I use xlsx.js along with dojo (js.arcgis.com/3.14compact/) and AMD i am getting below error
Uncaught TypeError: XLSX.read is not a function
    at ProcessExcel (ADBInitExcel.js:52)
    at FileReader.reader.onload (ADBInitExcel.js:26)

The html file and the script file is attached below
[InitialPage.zip](https://github.com/SheetJS/sheetjs/files/4596929/InitialPage.zip)

**Comment by SheetJSDev** [comment]
The fix is fairly straightforward and we'll accept a PR: the define call in https://github.com/SheetJS/sheetjs/blob/master/bits/99_footer.js#L6 should be

```js
else if(typeof define === 'function' && define.amd) define(function() { if(!XLSX.version) make_xlsx_lib(XLSX); return XLSX; });
```

**Comment by adeebgithub** [comment]
Hi SheetJSDev

It worked. Thanks for the immediate support

**Comment by SheetJSDev** [comment]
The original line was changed in #2405 for some RequireJS support, so it is now

```js
else if(typeof define === 'function' && define.amd) define('xlsx', function() { if(!XLSX.version) make_xlsx_lib(XLSX); return XLSX; });
```

https://github.com/SheetJS/sheetjs/blob/master/bits/99_footer.js#L6

@diaconori The rest of this comment will be added to the ["AMD" installation section](https://docs.sheetjs.com/docs/getting-started/installation/amd) and an example will be added to the ["bundlers" demo](https://docs.sheetjs.com/docs/demos/bundler). Please let us know if the explanation is clear and if we need to add anything else.

For legacy deployments and modern deployments using `async: 0`, calling `require` will add `XLSX` to the global scope

```html
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js" data-dojo-config="isDebug:1, async:0"></script>
<script>
  require(["https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"], function() {
    console.log(window.XLSX.version);
  })
</script>
```

With `async: true`, since the library explicitly sets the path to `'xlsx'`, a package configuration must be used.  To pull from the SheetJS CDN directly:

```html
<script>
  dojoConfig = {
    packages: [
      {
        name: "xlsx",
        // if self-hosting the script, location should be a folder relative to baseUrl setting
        location: "https://cdn.sheetjs.com/xlsx-latest/package/dist",
        // name of the script (without the .js extension)
        main: "xlsx.full.min"
      }
    ]
  }
</script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js" data-dojo-config="isDebug:1, async:1"></script>
<script>
  require(["xlsx"], function() {
    console.log(XLSX)
  });
</script>
```
