### ISSUE TITLE
Parsing CSV file , long numbers converted to another format

### ISSUE THREAD

**Issue by eldhoseelias** [SheetJS/sheetjs#2019]
number in csv 32349329483222222222342343242235
and it's read as '3.2349329483222224e+31'

how can i read it as same format/text
`const wb: XLSX.WorkBook = XLSX.read(bstr, { type: 'binary' });`

**Comment by garrettluu** [comment]
Hi there! This behavior is inherent to how JS numbers work; every number is a 64-bit IEEE754 double, but your number requires significantly more bits to represent it (about 105), so the number gets rounded. (More info about floating point numbers [here](https://en.wikipedia.org/wiki/IEEE_754))

Regarding how to parse the value as a string, use the `{raw: true}` option to parse everything as plain text. For example, 
```XLSX.read("asdf,32349329483222222222342343242235", {type: 'string', raw: true}```
will parse the first cell as normal, but parse the second cell as plain text instead of a number.
