### ISSUE TITLE
scientific notation problem

### ISSUE THREAD

**Issue by sibelius** [SheetJS/sheetjs#2078]
I'm getting some numbers in scientific notation

5512940468989 transforms into `5.51294E+12`

related to https://github.com/SheetJS/sheetjs/issues/1833

Sheet2JSONOpts

raw: true gives this trouble

**Comment by SheetJSDev** [comment]
That looks like the text under the General number format.  Can you share the cell object corresponding to that cell? For example, if that's cell A3 in your worksheet, `console.log(worksheet["A3"])`

**Comment by sibelius** [comment]
`K3: { t: 'n', v: 5512940468989, w: '5.51294E+12' },`

**Comment by SheetJSDev** [comment]
This is intended and follows Excel's behavior:

<img width="263" alt="" src="https://user-images.githubusercontent.com/6070939/89325616-0c97df80-d657-11ea-894b-24ae7da61ae1.png">

```js
var cell = { t: 'n', v: 5512940468989, w: '5.51294E+12' };
var ws = { A1: cell, "!ref":"A1" };
XLSX.utils.sheet_to_json({A1:, "!ref":"A1"}, {header:1, raw: true})[0][0]
```

When `raw: true` is specified, the result is the original number `5512940468989`.

When `raw: false` is specified, the value is the formatted text `5.51294E+12`, which is the entire point -- you're getting back the text that Excel uses.  And since the number format is not specified, it defaults to `General`.

If you'd like to change the format, wipe out the "w" field and use a different number format:

```js
// this replicates "Number" with no decimal places
var cell = { t: 'n', v: 5512940468989, z: '0' };
// this replicates "Number" with 2 decimal places
var cell = { t: 'n', v: 5512940468989, z: '0.00' };
// this replicates "Number" with thousands separator
var cell = { t: 'n', v: 5512940468989, z: '#,##0' };
```
