### ISSUE TITLE
UnDelete issue #2094

### ISSUE THREAD

**Issue by anthonybudd** [SheetJS/sheetjs#2095]
"Open Source" should be open. Deleting issues from public view is super shady and unethical.

You can't just brush an issue under the rug and expect it to go away, especially when other people have raised the same issue too over multiple years.

**Comment by SheetJSDev** [comment]
Quite honestly, the issue was deleted for your benefit.  It is extremely inappropriate and entitled to push volunteers to do more work.  You aren't a paying customer, you are using a free piece of software that was only possible due to the charity of our families and respective companies.  Comments like "You're just being lazy" are unnecessarily antagonistic and are exactly why many open source developers left the scene.  Good luck and hopefully you will reconsider your attitude in future interactions with the open source community.
