### ISSUE TITLE
How to detect a valid sheet file?

### ISSUE THREAD

**Issue by pnhuyduy** [SheetJS/sheetjs#2114]
Like if someone upload a `.exe` file but names it as `.xlsx`
How do I validate data in that file is from a valid sheet?

**Comment by SheetJSDev** [comment]
Magic number checks are used to determine file types.  https://github.com/SheetJS/sheetjs/blob/master/bits/87_read.js#L84 is the main switchboard.

MS-DOS and windows executables will not be confused with XLSX/XLSB/XLSM/ODS since they are ZIP files starting with `\x50\x4B` (PK) while executables start with `\x4D\x5A` (MZ).
