### ISSUE TITLE
xlsx 0.14.3 contains bug when parsing date field

### ISSUE THREAD

**Issue by krainboltgreene** [SheetJS/sheetjs#2153]
The value of my date field is `11/13/2020` or as xlsx `G3: {t: "n", v: 44148, w: "11/13/20"}`, however when I use `cellDates: true` I get this value: `G3: {t: "d", v: Thu Nov 12 2020 23:00:00 GMT-0800 (Pacific Standard Time), w: "11/13/20"}`

Is this a DST thing? If so, why doesn't it screw up other dates in my sheet? `F3: {t: "d", v: Mon Oct 19 2020 00:00:00 GMT-0700 (Pacific Daylight Time), w: "10/19/20"}`

**Comment by SheetJSDev** [comment]
The dates are currently anchored to Excel's 0 time, which causes numerous problems because 1900 occurred before timezone standardization for a number of timezones (https://github.com/SheetJS/sheetjs/issues/2160 discusses Bogotá in Colombia).  Can you share what the number value for `F3` was (basically, what is the cell value when `cellDates: false` is passed?)

**Comment by krainboltgreene** [comment]
Hilarious! `F3: {t: "n", v: 44123}`.

**Comment by flaushi** [comment]
https://github.com/SheetJS/sheetjs/issues/2196

**Comment by SheetJSDev** [comment]
There are a number of threads discussing date issues.  Closing in favor of #1565 .  The fix is going to involve reanchoring to some time which doesn't cause issues with V8
