### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by michaeldesu** [SheetJS/sheetjs#2217]
I've come across SheetJS via the Deno [third-party modules](https://deno.land/x/sheetjs). However there's no example or usage for deno. Is it possible to use with Deno? Apparently Deno prefers code imports that conform to ES modules. I've tried to use SheetJS via [skypak.dev](https://www.skypack.dev/view/xlsx) which can sometimes help convert node packages to modern ES modules, but I can't get the import to work, so sample code doesn't work. https://jspm.org/ might be another option. Unfortunately I'm learning server-side JS and Deno. Appreciate any tips to get it working on Deno. Thanks.

**Comment by michaeldesu** [comment]
FYI found this [trail](https://gitter.im/denolife/Lobby?at=5d46d139e939ab2447f4b009) (about 10 from that point) which has some diagnosis - looks like it's not possible currently

**Comment by thouger** [comment]
same problem..

**Comment by Wattenberger** [comment]
we have SheetJS working with Deno v1.10.x here, in case it helps either of you:

https://github.com/githubocto/flat-postprocessing/blob/main/src/xlsx.ts

**Comment by SheetJSDev** [comment]
Assuming the next release will have actual ESM builds and a proper `module` reference in package.json, what else is needed for Deno support?

**Comment by SheetJSDev** [comment]
Consider the following sample:

```ts
import * as XLSX from 'https://jspm.dev/npm:xlsx@0.18.0!cjs';

const rawdata = Deno.readFileSync("test.xlsb");
const wb = XLSX.read(rawdata, {type: "buffer"});
const buf = XLSX.write(wb, {type: "buffer", bookType: "fods"});
await Deno.writeFileSync("test.fods", new Uint8Array(buf));
```

This currently works with release 0.18.0 on deno 1.10.3 + typescript 4.2.2 with the following command:

```bash
$ deno run --allow-read --allow-write test.ts
```

It is also possible to reference the ESM build directly:

```typescript
import * as XLSX from 'https://unpkg.com/xlsx/xlsx.mjs';
```

Issues:

1) importing the full or any of the other commonjs bundles gives type errors due to confusion with the CFB module types.  This is a typedef issue and should be revisited. (it's actually unclear why Deno does this, bug in the runtime?)

2) Deno does not present a global equivalent of the NodeJS Buffer, which results in the fallback array-of-bytes when writing with type "buffer".  That needs to be revisited for each of the major export file types (there are a handful of areas that generate output stubs and they should be explicitly verified)

3) `Deno.readFileSync` / `Deno.writeFileSync` should be baked into the library.  The write call (guarded behind a typeof check for `Deno` and any other recommended tests for detecting a Deno runtime) should be put somewhere [in `write_dl`](https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L13) while the read call should be put somewhere [in `read_binary`](https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L52)

**Comment by SheetJSDev** [comment]
pushed a special tag `v0.18.0+deno` and added a new [`deno` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/deno)

```ts
// @deno-types="https://deno.land/x/sheetjs@v0.18.0+deno/types/index.d.ts"
import * as XLSX from 'https://deno.land/x/sheetjs@v0.18.0+deno/xlsx.mjs';
import * as cptable from 'https://deno.land/x/sheetjs/dist/cpexcel.full.mjs';
XLSX.set_cptable(cptable);

const ws = XLSX.utils.aoa_to_sheet([["a","b","c"],[1,2,3],[4,5,6]]);
const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "test.xlsx");
const workbook = XLSX.readFile("test.xlsx");
XLSX.utils.sheet_add_aoa(workbook.Sheets["Sheet1"], [[7, 8, 9]], { origin: -1 });
XLSX.writeFile(workbook, "test1.xlsx");
```

The other discussed issues will be raised separately
