### ISSUE TITLE
Non date data shows as date

### ISSUE THREAD

**Issue by betsonserviceportal** [SheetJS/sheetjs#2225]
Our ERP produces a .csv file containing these two rows.  

`"EIK","IMP","06-8108","IMP  06-8108","#658T MINI LAMP",6.000,.0860,.0860,.52,"710","IMP 16"`
`"MAR","MAR","250028162P","MAR  250028162P","BELT 143T MXL",1.000,1.8140,1.7690,1.77,"710","MAR 3"`

When I open the the .csv file with Excel the "06-8108" in the first row becomes "Jun-08".  In the second row "MAR 3" becomes "3-Mar".

I use js-xlsx for other tasks, so I figured I'd run it through and see if it fixed my issues.  I have a very simple script:

```
var XLSX = require('xlsx'),
    source = '/INVTRY710.csv',
    destination = '/INVTRY710_test.xlsx';

try {
    workbook = XLSX.readFile(source);
    console.log(JSON.stringify(workbook));
    XLSX.writeFile(workbook, destination);
    success = true;
} catch (e) {
    success = false;
    error = e.toString();
}
```

This fixes the issue with "06-8108",
`
			"C12": {
				"t": "s",
				"v": "06-8108"
			},
`

but not the "MAR 3".  
`
			"K18": {
				"t": "n",
				"v": 36953,
				"w": "3/3/01"
			},
`

**Comment by flaushi** [comment]
related https://github.com/SheetJS/sheetjs/issues/2196

**Comment by SheetJSDev** [comment]
Pass the option `raw: true`.  This will lift all values up to strings, which means `1.000` will be the text value rather than the numeric, but the possible date strings will not be touched.

PS: in general, the goal is to mirror Excel parsing rules by default, and many of the tests consist of generating a CSV using Excel and ensuring that SheetJS generates the same CSV
