### ISSUE TITLE
Crash on IOS OS

### ISSUE THREAD

**Issue by nazersingh** [SheetJS/sheetjs#2226]
When I am trying to Create a Excel File from Arrays. it is crashing on IOS OS when Creating Excel Sheet More than 250 rows. 

data is a object array;

        var ws = XLSX.utils.json_to_sheet(data);
        var wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'wireframe');
        var wbout = XLSX.write(wb, { type: 'array', bookSST: true, bookType: 'xlsx' }); // crashing here

**Comment by nazersingh** [comment]
On IOS OS Crash Log.

Process:               Adobe XD [8005]
Path:                  /Applications/Adobe XD/Adobe XD.app/Contents/MacOS/Adobe XD
Identifier:            com.adobe.xd
Version:               36.2.32.5 (36.2.32.5)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Adobe XD [8005]
User ID:               501

Date/Time:             2021-02-03 15:30:29.675 +0100
OS Version:            macOS 11.2 (20D64)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        E6C394D4-50D4-6FAA-2043-4F0CA7EF9CA5

Sleep/Wake UUID:       B2513F64-761A-4F79-AE89-2A6A261ECAE8

Time Awake Since Boot: 26000 seconds
Time Since Wake:       3800 seconds

System Integrity Protection: enabled

Crashed Thread:        48  V8 Manager Thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000070000e891ff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [8005]

**Comment by SheetJSDev** [comment]
This is very likely an issue with Adobe XD, but to confirm let's do a small test.  Can you dump a JSON serialization of the workbook object (`JSON.stringify(wb)`), write it to a file, then try to export using your browser?  For example, lets say data was

```js
[
  { a: 1, b: 2 },
  { a: 1, c: 2 }
]
```

Instead of calling `XLSX.write`, generate the JSON for the workbook object:

```js
    var wb_json = JSON.stringify(wb);
```

Then export that data using something like `console.log(wb_json)` if you have console access.  In this example the string would be

```json
{"SheetNames":["wireframe"],"Sheets":{"wireframe":{"A2":{"t":"n","v":1},"B2":{"t":"n","v":2},"A3":{"t":"n","v":1},"C3":{"t":"n","v":2},"A1":{"t":"s","v":"a"},"B1":{"t":"s","v":"b"},"C1":{"t":"s","v":"c"},"!ref":"A1:C3"}}}
```

Save that string to a file, then use https://jsfiddle.net/5x19fwL8/ to generate the XLSX export.  It's super simple, there's a file input element and the following code is run when you upload the JSON:

```js
document.getElementById("import").addEventListener("change", (evt) => {
  var fr = new FileReader();
  fr.onload = (e) => {
    var wb = JSON.parse(e.target.result);
    XLSX.writeFile(wb, "issue2226.xlsx");
  }
  fr.readAsText(evt.target.files[0]);
});
```

If this works, you will have to ask @AdobeXD to investigate further.

**Comment by SheetJSDev** [comment]
Please follow up with @AdobeXD support
