### ISSUE TITLE
In what circumstances will this error be triggered and what is the error content?

### ISSUE THREAD

**Issue by wish-cheng** [SheetJS/sheetjs#2325]
Source code:
```
case 'Password':
	if (val !== 0 && opts.WTF) console.error("Password verifier: " + val);

```
sheetjs v0.15.5

What's "Password" represent for? 
Whether the "val" contains plaintext password?

**Comment by SheetJSDev** [comment]
That is from the XLS parser.  "Password" is record type `0x13` as explained in [MS-XLS 2.4.191](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/1d0e4db7-cc6a-4143-b72c-27d972f72f05)

You may find this show up with normal files that do not have a workbook password.  If a file is marked as "read-only" Excel will actually encrypt using the password "VelvetSweatshop".

Due to the general size and complexity of supporting XLS / XLSX / ODS encryption, it is not something we plan to add to the open source build anytime soon, but we do offer password-protection support as part of our [Pro compendium](https://sheetjs.com/pro)
