### ISSUE TITLE
Demo Broken

### ISSUE THREAD

**Issue by BFinnigan** [SheetJS/sheetjs#2337]
When I upload the attached (admittedly unusual) file, the demo page ( https://oss.sheetjs.com/sheetjs/ ) just crashes.
[bad_cell.xlsx](https://github.com/SheetJS/sheetjs/files/6895605/bad_cell.xlsx)

We occasionally encounter a similar issue where the file we are processing has ~1 million blank rows and the processing times out.

**Comment by SheetJSDev** [comment]
The bad cell is in address XFD1048576.  Due to V8 caching small strings, Chrome ends up generating and retaining almost 4.3M cell addresses even if they are not in the worksheet.

Passing the option `dense: true` when parsing will use an array of arrays under the hood, which should avoid the problematic loop.
