### ISSUE TITLE
Feature request: Use semantic versioning.

### ISSUE THREAD

**Issue by coolaj86** [SheetJS/sheetjs#2344]
At 26.8k stars and a million bajillion downloads... isn't it time to let us know when there will or won't be a breaking change by the version number?

Can we get a `v1.x`? Please? 😄

**Comment by SheetJSDev** [comment]
To be absolutely fair, 0.x.y is still under the purview of semantic versioning.  Backwards incompatible changes are marked with the "minor" version.  The 0.17.0 release was a bump because it changed parts of the read resolution process.

As for v1.0.0, there's a long wishlist and it's unclear what should be changed before the version bump.  One of the most glaring and practical issues is browser support.  We still test against older browsers that were relevant in 2012 but aren't relevant in 2021.  Issues with transpiled code in older browsers prevent us from shifting to an ESM codebase.  Ideally we'd have separate modules for each file format and the end user would be able to make targeted builds (or even use dynamic imports).
