### ISSUE TITLE
Redefine style.xml?

### ISSUE THREAD

**Issue by m-orsh** [SheetJS/sheetjs#2345]
I've got a style.xml file ready to go for an xlsx export download. Is there any way to apply this on a generated xlsx file via sheetjs? Or is that specifically a pro feature? I see the themeXLSX export option, but I think this is for theme.xml, not style.xml within the .xlsx file. I'm wondering why theme.xml is settable on the community edition, but not style.xml, unless I'm missing something.

**Comment by SheetJSDev** [comment]
There's a [longer discussion](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021) about why styles in general is part of our Pro software, but in summary companies have paid us for software specifically to address styling and it seems unfair to make those parts open source (in the same way that it seems inappropriate to take an open source project and turn it closed-source, which has been a troubling trend over the last few years).

As for the specific question of overriding the `styles.xml` file, some of the calculations like column widths and comments are tuned for the case of Calibri 12 as the "first" font.  https://github.com/SheetJS/sheetjs#column-properties talks about column widths (expand "Why are there three width types?").  Repeating the relevant paragraph:

> XLSX internally stores column widths in a nebulous "Max Digit Width" form. The Max Digit Width is the width of the largest digit when rendered (generally the "0" character is the widest). The internal width must be an integer multiple of the the width divided by 256.

As JavaScript developers, we're familiar with web units, so from a design perspective we thought it important to translate from Excel details to web-friendly data when possible.  This only really works on the export side if we control Excel styling details on export.  If you're wondering why we can't just use a CANVAS `measureText`, aside from applicability in NodeJS or older IE or PhotoShop, it turns out "Calibri the web font" has different metrics from "Calibri the font embedded in Excel".  Licensing constraints prevent us from embedding a "correct" Calibri font.  Google Docs tried to work around the problem with [Carlito](https://en.wikipedia.org/wiki/Croscore_fonts) but there are practical issues (do we have to embed the Carlito font or can we assume computers have it? Is OFL, the primary license on the Carlito font, compatible with Apache 2.0?  Are the versions metric-compatible with the web font or the Excel font?)

Themes do not affect the metrics, which is why one can be overridden but not the other.
