### ISSUE TITLE
XLSX file protected view cannot read

### ISSUE THREAD

**Issue by Giulo77** [SheetJS/sheetjs#2376]
if i try to read an excel file in protected view i get this error:
`var workbook = XLSX.read(data, {type: 'binary'});

Uncaught Error: Unknown Namespace: 
    at Kd (xlsx.full.min.js:18)
    at op (xlsx.full.min.js:19)
    at ig (xlsx.full.min.js:22)
    at cg (xlsx.full.min.js:22)
    at Object.gg [as read] (xlsx.full.min.js:22)
    at ProcessExcel (ImportFatture.php:97)
    at FileReader.Upload.reader.onload (ImportFatture.php:60)`

The file is called test.xlsx and if I open it and enable the modification and save the file everything works correctly.
The problem is that I wanted to automate the import by skipping this manual step and since the library I need to read the content I'm not editing anything so I shouldn't have such an error.

**Comment by SheetJSDev** [comment]
Can you share the file?

**Comment by Giulo77** [comment]
I have tried in every way to replicate the same excel file but I have not really succeeded. Unfortunately it comes from an export from a management software and contains sensitive data so I can't really share it.

**Comment by SheetJSDev** [comment]
https://oss.sheetjs.com/cfb-editor/ is an in-browser tool for viewing archives (everything runs in your browser).  Drag-drop the bad file into the window.

Based on the error message, it is likely coming from `[Content_Types].xml` or `xl/workbook.xml`.  It would be helpful to look at those.  Since both are text files, you can manually scan them for sensitive data

To download, click on `[Content_Types].xml` in the left column, then click "Export Entry" and it will download `[Content_Types].xml`.  Repeat the process for `xl/workbook.xml` and it will download `xl_workbook.xml`.  You can email both to hello@sheetjs.com

**Comment by ansarikhurshid786** [comment]
I am facing same issue on web server. local server working fine.

**Comment by reviewher** [comment]
@ansarikhurshid786 please share a sample file and details about your web server.  Is it running on AWS or some other cloud host?

**Comment by ansarikhurshid786** [comment]
I am still facing issue. anyone has solution

**Comment by ansarikhurshid786** [comment]
> @ansarikhurshid786 please share a sample file and details about your web server. Is it running on AWS or some other cloud host?

It is windows server. Problem normal excel file and for cvs file working fine.

**Comment by SheetJSDev** [comment]
Please test against the latest version (follow instructions https://docs.sheetjs.com/docs/getting-started/#installation ).  If the issue persists, please share a file (email hello@sheetjs.com or create a new issue) and we can take a closer look
