### ISSUE TITLE
Double quotation on json cell when generating csv

### ISSUE THREAD

**Issue by MatiasLima2594** [SheetJS/sheetjs#2396]
Im trying to generate a csv from a worksheet with an json array of objects and they get double quatation.

`csvdata = XLSX.utils.sheet_to_csv(sheetdata, { FS: ";", RS: "\n" });`

This is the data in the cell:
`'[{"email":"andres.laplace@gmail.com", "status":"0", "description":" "},{"email":"andres.laplace@gmail.com", "status":"0", "description":" "}]'`

What i expect:
`"[{"email":"example@gmail.com", "status":"0", ""description":" "},{"email":"example@gmail.com", "status":"0", "description":" "}]"`

What i get:
`"[{""email"":""example@gmail.com"", ""status"":""0"", ""description"":"" ""},{""email"":""example@gmail.com"", ""status"":""0"", ""description"":"" ""}]"`

**Comment by SheetJSDev** [comment]
Maybe the question is unclear (it would help to attach an actual XLSX starting file) but this is expected behavior.  When a double-quote `\x22` or the field or row separator characters are in a cell, the entire cell is wrapped in double-quotes.  Literal double-quote characters are doubled as that is how you "escape" the character with Excel.

For what it's worth, [RFC4180](https://datatracker.ietf.org/doc/html/rfc4180#section-2) also demands the doubling:

```
   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```
