### ISSUE TITLE
Compatible with Android browser

### ISSUE THREAD

**Issue by GHzhuzhu** [SheetJS/sheetjs#2443]
It is not compatible with Android browser and can be used on PC and iPhone ， i use React and it can't download or  the file cannot be used normally, directly to open or not open garbled with Android . How can I fix it? looking for  answer，grateful！

**Comment by reviewher** [comment]
Does the react-native demo from https://github.com/SheetJS/sheetjs/tree/master/demos/react work for you?

**Comment by SeniorChiefABLEUnit** [comment]
Workbook in hand. Waiting on confirm from AAL, Space X

**Comment by GHzhuzhu** [comment]
I solve it with google Android and wps app

**Comment by SeniorChiefABLEUnit** [comment]
Sounds great. Accept.

**Comment by SeniorChiefABLEUnit** [comment]
The movies are awesome, the great scripts have eyes from seasoned &
experienced, as well. Interesting that it takes so little effort to open a
door. These should continue, and will grow, word is spreading so they can
know.
It still does not pay my bills, the kids know that these things exist.
Stay focused, stay vigilant. Credentials are great, real world hands on can
NOT be beat. The focus I have is mine to spread, time to go now, off to bed.
Checking for mail, since the Eagle flew, has grown tiresome, somI continue
to look up.
The up is not down , it is the sea,
The see I see is the beginning of new,
Stay focused, means so little to few,
You , I do not know, then we know.
So many minds that are completing instructions wrong. Sometimes it is vest
to not want to see.
It is best to just let things grow.
The avalanche of time will be the stone, I chisel my knife to continue to
throw.
