### ISSUE TITLE
CSV file has a "ZERO WIDTH NO-BREAK SPACE" at beginning of header row

### ISSUE THREAD

**Issue by kennethkeim** [SheetJS/sheetjs#2620]
I guess the first question is: should this character be here?

I found the issue by using [this code](https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line) to read the file one line at a time and do: `line.charCodeAt(0)` on each line.
Excel doesn't seem to care, but Transaction Pro (an importer for QuickBooks) sees the character as `ï»¿` and it's causing my QB import to fail.

I'm happy to provide more details if needed, but wanted to check if the character is supposed to be there.

**Comment by SheetJSDev** [comment]
That is the [binary string encoding of the UTF8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8):

```js
"ï»¿".split("").map(x => x.charCodeAt(0).toString(16))
// ["ef", "bb", "bf"]
```

This is written by default because Excel interprets CSV files in the local codepage by default.  You have to insert the BOM for Excel to treat the file as UTF8.

The actual character is inserted by the `write` and `writeFile` functions.  If you want the CSV without the BOM, use `XLSX.utils.sheet_to_csv` directly or ask for a return type `string`:

```js
var ws = XLSX.utils.aoa_to_sheet([["A","B"],[1,2]]);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

/* this inserts BOM */
XLSX.write(wb, {type: "binary", bookType: "csv"})
// 'ï»¿A,B\n1,2'

/* the "string" type returns a normal string without BOM */
XLSX.write(wb, {type: "string", bookType: "csv"})
// 'A,B\n1,2'

/* this returns a normal string */
XLSX.utils.sheet_to_csv(ws)
// 'A,B\n1,2'
```

This really should be explained somewhere in the documentation, probably in "Delimited-Separated Output".  Feel free to send a PR.

**Comment by kennethkeim** [comment]
Thanks so much. Getting back so quickly saved me a lot of time.
