### ISSUE TITLE
The Numbers writer is currently limited to A1:J50

### ISSUE THREAD

**Issue by HappyFerry** [SheetJS/sheetjs#2719]
when open .xlsx file, and save to numbers format file. 

> XLSX.writeFile(wb, dist, {numbers: XLSX_ZAHL, compression: true});

it can save to .numbers in mac osx, but just limited A1:J50 area data, other data is disapper, and sheet style is gone.

how to remove limiting , and take the .xlsx sheet style into .numbers ?

**Comment by SheetJSDev** [comment]
The Numbers program only supports A1:ALL1000000  (ALL maps to the 1000th row, SheetJS index 999), so you can't write outside of that range.

The library (version 0.18.9) currently supports A1:ALL255 .  To go beyond that (and eventually, to support number formats and other features), we need to look into the required properties to support multiple tiles.

**Comment by HappyFerry** [comment]
😯,the point is XLSX_ZAHL.js ？can i extend 1000000, it 's only want to save data without any property。or let me to read some document todo, thanks.

**Comment by SheetJSDev** [comment]
If there were actual documentation, this would be a straightforward task.  Unfortunately, Apple has not released anything.  We've been trying to document stuff at https://oss.sheetjs.com/notes/iwa/ but the understanding is pretty superficial at this point.

The writer currently works by taking a known NUMBERS file and modifying the bare minimum to force Numbers to refresh the file and use the new data.  Since NUMBERS is not a common file format, it did not make sense to add an additional 100KB to the size of the browser build by default.  The final design has a separate script which holds the NUMBERS template, which is passed into `write` or `writeFile` and used for the "numbers" export book type.

We'll take a closer look at multiple tiles when we revisit Numbers.

**Comment by HappyFerry** [comment]
ok, thanks for your clarification

**Comment by HappyFerry** [comment]
ok, thanks for your clarification

**Comment by SheetJSDev** [comment]
In 0.18.12 we resolved the range cap.  You should be able to write up to 1000 columns and up to 1000000 rows in a single table (this is a limitation of the app).  We're definitely interested in writing multiple sheets.
