### ISSUE TITLE
Support for exposing or limiting file format on read

### ISSUE THREAD

**Issue by marc-mabe** [SheetJS/sheetjs#2734]
Hi,

We are using this library to validate and preview a selected file in the browser before actually uploading it.
Of course we limit the supported formats on file selection side (with uppy) but this is not 100% accurate in all cases.

It would be great to have the possibility to either limit the supported file formats on reading so that we can show a proper error message to the user before actually uploading the file or exposing the used file format so that we can check our self which one was detected by sheetjs.

Thanks for your help!

**Comment by marc-mabe** [comment]
> If there are parsing errors, please share any files (those are most likely library isuses)

Actually I mean the opposite. Also it doesn't matter what excel (or any other application) does in this case.
 
The point is that we get a file uploaded into our web application that we need to parse (happens in the backend) and store in a DB table. For that we only support xlsx and to make sure a valid file for our use case file gets uploaded we want to validate the file and preview the content incl. errors per cell to the user.

To have a proper workflow we need to make sure it's handled (as much as possible) the same way on the frontend as on the backend. For that we want to limit the possible file types on the frontend to xlsx so that we accept a format which works stable on both ends.

As sheetjs already does file format detection it would be very helpful to expose that to users so that we can detect it.

Something like this:
```
file.arrayBuffer().then((arrayBuffer) => {
    const workBook = read(arrayBuffer);
    workBeek.format; // XLSX, ODS, CSV, ...
});
```


As example: If I know create a file in ods format and change the extension to xlsx it going throw the upload and only file on backend as it's a supported file extension and sheetJS can read it but the backend doesn't understand what it is.

**Comment by SheetJSDev** [comment]
You could also run SheetJS on the server side using NodeJS or Deno 😅 

Since `bookType` is used by the writer to indicate the desired output format, maybe that should be the property name?

https://github.com/SheetJS/sheetjs/blob/master/bits/85_parsezip.js#L250 is a good spot to resolve and add the marker.  At that point, the workbook is either XLSB or XLSM / XLSX (test `xlsb` variable).  You can test for macros by looking at `dir.vba`.

**Comment by SheetJSDev** [comment]
Will be live in the next release.  Types reflect the [new workbook property](https://github.com/SheetJS/sheetjs/blob/master/types/index.d.ts#L289-L290):

```typescript
/** Workbook Object */
export interface WorkBook {
    // ...
    /** Original file type (when parsed with `read` or `readFile`) */
    bookType?: BookType;
}
```

There are still a few open questions on similar formats:
- should XLSX / XLSM be separate?
- how should the BIFF2/3/4/5/7/8 XLS formats be handled?
- should the Lotus / DOS Quattro Pro / DOS and early Windows Works files be distinguished?

The history around the Lotus style is particularly hairy since a number of spreadsheet software used the original BOF flag (pretending to be official Lotus files with some extensions).

That said, commit ad1ce0d addresses the immediate problem of XLSX/XLSM versus other formats.

**Comment by marc-mabe** [comment]
This works nicely for my use case - thanks :+1: 


> There are still a few open questions on similar formats:
> 
>     * should XLSX / XLSM be separate?
> 
>     * how should the BIFF2/3/4/5/7/8 XLS formats be handled?
> 
>     * should the Lotus / DOS Quattro Pro / DOS and early Windows Works files be distinguished?

In my opinion it should report the same book types as are supported on creating a work book.
