### ISSUE TITLE
How to Write Files in Web Workers

### ISSUE THREAD

**Issue by HessamCheraghi** [SheetJS/sheetjs#2743]
Hi, I'm using using xlsx for relatively large number of data in browser, I decided to use with web workers for performance. during my testing I found out that only writing the file to xlsx takes a lot of time, is there any way to use `XLSX.writeFile` inside the web worker? 
because when I use it inside web workers I get this error:

```error
xlsx.mjs:3239 Uncaught Error: cannot save file sheet.xlsx
    at write_dl (xlsx.mjs:3239:1)
    at write_zip_denouement (xlsx.mjs:24982:1)
    at write_zip_type (xlsx.mjs:24952:1)
    at writeSync (xlsx.mjs:25089:1)
    at writeFileSync (xlsx.mjs:25112:1)
    at show (web-worker.js:54:1)
    at onmessage (web-worker.js:64:1)
```

**Comment by SheetJSDev** [comment]
There is no standard browser API for writing files.  SheetJS tries to use the HTML5 download attribute trick in modern browsers: create `<a>` element, set the link to a blob URL and set the `download` attribute to the desired filename, then add to the dom and `click` it.  https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L28 is where the relevant code starts, and the path is:

```js
	var blob = new Blob([data], {type:"application/octet-stream"});
	var url = URL.createObjectURL(blob);
	var a = document.createElement("a");
	a.download = desired_filename;
	a.href = url;
	document.body.appendChild(a);
	a.click();
```

**This does not work in web workers** since they do not have DOM access.

Instead, do the write in the web worker with the array type:

```js
// in the web worker, generate the XLSX file as a Uint8Array
const u8 = XLSX.write(workbook, { type: "array", bookType: "xlsx" });
```

Then send it back to the main thread:

```js
// in the web worker, send the generated data back to the main thread
postMessage({t: "export", v: u8 });
```

Then from the renderer worker interface, do the export:

```
// in the main page
worker.addEventListener('message', function(e) {
  if(e && e.data && e.data.t == "export") {
    e.stopPropagation();
    e.preventDefault();
    // data will be the Uint8Array from the worker
    const data = e.data.v;

    var blob = new Blob([data], {type:"application/octet-stream"});
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.download = desired_filename;
    a.href = url;
    document.body.appendChild(a);
    a.click();
  }
});
```

If this makes sense, please let us know how to update the README to add this note.

**Comment by HessamCheraghi** [comment]
Yes this is exactly what I was looking for.
during my test I found out that using web worker is slower than the main thread, but UI and other tasks won't get stuck.

![Annotation 2022-07-14 202425](https://user-images.githubusercontent.com/62061093/179024907-d532fedf-b8ea-460b-b9d8-762a7a808030.png)


also I created a live example of my tests  [here](https://hessamcheraghi.github.io/SheetJS-web-worker/) .

**Comment by SheetJSDev** [comment]
This should probably be added to the documentation.  Where is the best place to include a note about web workers?  (it also makes sense to add a note about using `FileReaderSync` in a web worker for parsing)

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/solutions/output#example-local-file
