### ISSUE TITLE
xlsx-cli should not depend on "latest" version of xlsx

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [SheetJS/sheetjs#2753]
The `xlsx-cli` package depends on [the latest version of `xlsx`](https://github.com/SheetJS/sheetjs/blob/d55b7a306392bb4131ca5a41cc2fbea54c3e5a77/packages/xlsx-cli/package.json), which forces us to manually update our `yarn.lock` every time a new version of `xlsx` is released, which breaks our builds.

It would be preferable for `xlsx-cli` to select a specific version of `xlsx` and receive its own version bumps in tandem with `xlsx`.

**Comment by SheetJSDev** [comment]
npm inc froze the publishing accounts, so for all intents and purposes [`xlsx`](https://www.npmjs.com/package/xlsx), [`xlsx-cli`](https://www.npmjs.com/package/xlsx-cli), [`crc-32`](https://www.npmjs.com/package/crc-32), [`printj`](https://www.npmjs.com/package/printj), [`codepage`](https://www.npmjs.com/package/codepage), [`cfb`](https://www.npmjs.com/package/cfb), [`ssf`](https://www.npmjs.com/package/ssf), and the rest are stuck.

Since `xlsx-cli` is a CLI tool and the script generally plays nice with [standalone tools like `nexe` and `deno compile` and `pkg`](https://docs.sheetjs.com/docs/getting-started/demos/cli), we could make versioned standalone binaries available.  Alternatively we could publish `xlsx-cli` on https://cdn.sheetjs.com like how the main `xlsx` module is published today.

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/demos/cli describes how to build a dedicated executable using `deno compile` or NodeJS based command-line tool builders.
