### ISSUE TITLE
Large Excel Files (100 Mb) - Extracting partial information

### ISSUE THREAD

**Issue by amerj19** [SheetJS/sheetjs#431]
Hi

Can I read large excel files (around 100 MB)?  I tried with the sample but browser crashes.  I understand, I can read file in slices, however, I am not sure how to read information how to read data from each slice. e.g. cell values etc.  Is there a good example to read large excel files on client.

**Comment by fabriziomorello** [comment]
I have the same issue. Hope someone can help us.

**Comment by diegoles** [comment]
I have the same issue. Hope someone can help us.

**Comment by reviewher** [comment]
@amerj19 @fabriziomorello @diegoles I recommend trying to use the node-based tool first to make sure that the files can be read and that the issue is due to the size.  Alternatively you can email us or post a link to a file that crashes the browser.

As for the general question, the way the excel data is stored, you need to process quite a bit.  The container formats themselves (zip and cfb) are so flexible that a reader must load all of the data in memory (some write tools scatter metadata throughout the file).  In the XLSX case, you additionally have to read multiple sub-files to find the cell values.  So there's no obvious way to reduce memory consumption without radically changing the API surface.

**Comment by reviewher** [comment]
Combining all of these discussions about reading large files into one issue: #61
