### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by pjpastrana** [SheetJS/sheetjs#60]
I am having some difficulties getting the library to work properly from the browser.
I downloaded the latest build and tried including the core, full versions, as well as the jszip with xlsx and I get the same error (listed below). 
ReferenceError: require is not defined
var XLSX = require('xlsx');

TypeError: _fs is undefined
d = _fs.readFileSync(data).toString('base64');

Any thoughts as to what dependency I might be missing?
Thanks.

**Comment by JustinJmnz** [comment]
@SheetJSDev 
Hey, I was just going through this because I had the same problem. This solution didn't work for me. After adding the CDN, I still get the same error: `TypeError: _fs is undefined   xlsx.core.min.js:15:3896`

This is what my JavaScript looks like,

`if(typeof XLSX === 'undefined' && typeof require !== 'undefined') XLSX = require('xlsx');
	var workbook = XLSX.readFile('menu.xlsx');
	var sheet_name_list = workbook.SheetNames;
	console.log(XLSX.utils.sheet_to_json(workbook.Sheets[sheet_name_list[0]]))`

**Comment by SheetJSDev** [comment]
@JustinJmnz `readFile` only works in node, not in the browser.  You need to pull in data and use `XLSX.read`.  See https://github.com/SheetJS/js-xlsx#parsing-workbooks in the README for some examples and demo links.  In particular, http://oss.sheetjs.com/js-xlsx/ajax.html uses XHR and http://oss.sheetjs.com/js-xlsx/ uses the HTML5 File API
