### ISSUE TITLE
ODS Export Localization

### ISSUE THREAD

**Issue by LaioNWB** [SheetJS/sheetjs#692]
Hi,

I have to export a VALUE = xxxx.xxxx value into ODS file.
But when i'am exporting the file, the "VALUE" is like xxxx,xxxx instead of xxxx.xxxx.

When i inspect the object i see that :
`<table:table-cell office:value-type="float" office:value="51.01468"><text:p>51.01468</text:p></table:table-cell>`

But in file "51,01468"...
How can i have, in my exported file, "51.01468" for that column?

Regards

**Comment by SheetJSDev** [comment]
@LaioNWB what are your regional settings? JS always uses a period `.` as the decimal separator but your computer may be set to using a comma `","` as the decimal separator.

**Comment by LaioNWB** [comment]
SheetJSDev,

My regional settings are French... You think is about that, my settings format automatically?

**Comment by SheetJSDev** [comment]
@LaioNWB Long story short: the default number formats are localized, but drawn as a "." in the file.  So even if you set a format like "Number with 2 Decimal Places", the file itself stores "0.00" as the format irrespective of the computer settings, but Excel/LO displays the decimal character from the file.

This issue is still open because we need a better story for handling regional settings.  In theory [`Number#toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) should work, but in practice it doesn't seem to work in node.  From the German example: 

```js
var number = 123456.789;
console.log(number.toLocaleString('de-DE'));
```

This doesn't work in nodejs:

```js
"123,456.789" // nodejs under US settings
"123.456,789" // chrome under US settings
```

**Comment by LaioNWB** [comment]
I got it!

Thank you for explaination!
Have a nice day :)
