### ISSUE TITLE
format number 

### ISSUE THREAD

**Issue by cyzeng-Luca** [SheetJS/sheetjs#852]
i have a excel like this:
![image](https://user-images.githubusercontent.com/25954683/31885124-08b36d2c-b822-11e7-8cae-5765e88b1844.png)

but when i parse it
![image](https://user-images.githubusercontent.com/25954683/31885163-23e1b090-b822-11e7-8983-e6a7d4ed5a36.png)

the result is:
![image](https://user-images.githubusercontent.com/25954683/31885112-ff8caa56-b821-11e7-8ee4-8bc0f6ed5d3f.png)

i want to have the origin number not Scientific counting？ 
should i add some params?

**Comment by cyzeng-Luca** [comment]
add a condition:
   i have some cell is date ,if the cellNF true ,not date is wrong

**Comment by SheetJSDev** [comment]
With `cellNF: false` and `cellText: false`, `sheet_to_json` would have tried to generate new strings using the "General" format.  At least set `cellNF: true` to keep the original number formats.

PS: the default behavior of `sheet_to_json` has changed, so now it will return the raw values.  You have to set the option `raw: false` in order to get the strings.
